Replace `.Requires` with `ControlFlow.Assert` to check if `GitLatestTag` has value or not
Error: Assertion failed: Target 'BumpVersion' requires 'Not(IsNullOrWhiteSpace(value(Build).GitLatestTag))'.

Apparently `.Requires` is executed first before `.DependsOn`.